### ISSUE TITLE
Endian independency

### ISSUE THREAD

**Issue by TheGreatRambler** [eyalz800/serializer#5]
Just so I'm completely certain, does this library produce endian independent output, so I can serialize a struct on one endianess and parse it on the other?

**Comment by TheGreatRambler** [comment]
Any answer?

**Comment by eyalz800** [comment]
The library will not work if one system is little and the other is big, I might consider adding this functionality in the upcoming weeks when I have more free time, I'm also happy to review and accept commits that add this behavior.

**Comment by TheGreatRambler** [comment]
Fantastic, I've been using this library as the backbone of a networking imp and it works beautifully.

**Comment by eyalz800** [comment]
And you are running it on a big endian machine that communicates with little endian?

**Comment by TheGreatRambler** [comment]
I'm running it on a little endian machine that communicates with a little endian machine, however I want to extend support just in case.

**Comment by TheGreatRambler** [comment]
What's the use of `swap_byte_order` in the code?

**Comment by eyalz800** [comment]
The swap byte order is used to run the sha1 function inside make_id in compile time. @TheGreatRambler

**Comment by TheGreatRambler** [comment]
I was thinking of using these functions as I'm not any good at templates https://linux.die.net/man/3/endian

**Comment by eyalz800** [comment]
@TheGreatRambler I just took a brief look at the code again, it seems like multiple places need to be changed to support endian independency - 
Every place that has std::copy (4 places I think) need to create template specialization that for integers, will change the byte order from big to little. In addition, the serialization of containers that are trivially copyable (2 places) will need to change as well to be unoptimized and act like normal containers - and I expect that it will worsen the performance by far, again only on big endian machine . This will make sure that if big endian machine is communicating with little endian - the data will still be serialized like little endian

**Comment by eyalz800** [comment]
@TheGreatRambler do you have a big endian machine to test it on? So that if I make the change you can check?

**Comment by TheGreatRambler** [comment]
Perhaps a compile flag? I would be okay with a performance hit.

**Comment by eyalz800** [comment]
@TheGreatRambler I think I might have a solution, but I will want to test it somehow, do you have a machine to test it on?

**Comment by TheGreatRambler** [comment]
Ah, I do not

**Comment by eyalz800** [comment]
@TheGreatRambler in that case I would probably use the python library as a way to test but to be honest I don't think that we must do this right now instead of waiting for a real case
